---
- name: Fedora Workstation 40 configuration.
  hosts: localhost

  vars_files:
    - vars/main.yaml

  roles:
    - role: robertdebock.update
      update_reboot: false
      become: true
      tags: ['update']
    - role: gantsign.visual-studio-code
      tags: ['vscdoe']
    - role: darkwizard242.googlechrome
      tags: ['chrome']
      become: true

  tasks:
    - name: Install packages
      ansible.builtin.import_tasks:
        file: tasks/packages.yaml
    - name: Configure shell
      ansible.builtin.import_tasks:
        file: tasks/shell.yaml
